package com.vagrancys.learningassistant.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.vargancys.learningassistant.db.common.HelpCommendItem;
import com.vargancys.learningassistant.db.common.HelpContentItem;
import com.vargancys.learningassistant.db.home.HomeKnowContent;
import com.vargancys.learningassistant.db.home.HomeKnowItem;
import com.vargancys.learningassistant.db.home.HomeKnowData;
import com.vargancys.learningassistant.db.home.HomeKnowFunction;

import com.vagrancys.learningassistant.db.HelpCommendItemDao;
import com.vagrancys.learningassistant.db.HelpContentItemDao;
import com.vagrancys.learningassistant.db.HomeKnowContentDao;
import com.vagrancys.learningassistant.db.HomeKnowItemDao;
import com.vagrancys.learningassistant.db.HomeKnowDataDao;
import com.vagrancys.learningassistant.db.HomeKnowFunctionDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig helpCommendItemDaoConfig;
    private final DaoConfig helpContentItemDaoConfig;
    private final DaoConfig homeKnowContentDaoConfig;
    private final DaoConfig homeKnowItemDaoConfig;
    private final DaoConfig homeKnowDataDaoConfig;
    private final DaoConfig homeKnowFunctionDaoConfig;

    private final HelpCommendItemDao helpCommendItemDao;
    private final HelpContentItemDao helpContentItemDao;
    private final HomeKnowContentDao homeKnowContentDao;
    private final HomeKnowItemDao homeKnowItemDao;
    private final HomeKnowDataDao homeKnowDataDao;
    private final HomeKnowFunctionDao homeKnowFunctionDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        helpCommendItemDaoConfig = daoConfigMap.get(HelpCommendItemDao.class).clone();
        helpCommendItemDaoConfig.initIdentityScope(type);

        helpContentItemDaoConfig = daoConfigMap.get(HelpContentItemDao.class).clone();
        helpContentItemDaoConfig.initIdentityScope(type);

        homeKnowContentDaoConfig = daoConfigMap.get(HomeKnowContentDao.class).clone();
        homeKnowContentDaoConfig.initIdentityScope(type);

        homeKnowItemDaoConfig = daoConfigMap.get(HomeKnowItemDao.class).clone();
        homeKnowItemDaoConfig.initIdentityScope(type);

        homeKnowDataDaoConfig = daoConfigMap.get(HomeKnowDataDao.class).clone();
        homeKnowDataDaoConfig.initIdentityScope(type);

        homeKnowFunctionDaoConfig = daoConfigMap.get(HomeKnowFunctionDao.class).clone();
        homeKnowFunctionDaoConfig.initIdentityScope(type);

        helpCommendItemDao = new HelpCommendItemDao(helpCommendItemDaoConfig, this);
        helpContentItemDao = new HelpContentItemDao(helpContentItemDaoConfig, this);
        homeKnowContentDao = new HomeKnowContentDao(homeKnowContentDaoConfig, this);
        homeKnowItemDao = new HomeKnowItemDao(homeKnowItemDaoConfig, this);
        homeKnowDataDao = new HomeKnowDataDao(homeKnowDataDaoConfig, this);
        homeKnowFunctionDao = new HomeKnowFunctionDao(homeKnowFunctionDaoConfig, this);

        registerDao(HelpCommendItem.class, helpCommendItemDao);
        registerDao(HelpContentItem.class, helpContentItemDao);
        registerDao(HomeKnowContent.class, homeKnowContentDao);
        registerDao(HomeKnowItem.class, homeKnowItemDao);
        registerDao(HomeKnowData.class, homeKnowDataDao);
        registerDao(HomeKnowFunction.class, homeKnowFunctionDao);
    }
    
    public void clear() {
        helpCommendItemDaoConfig.clearIdentityScope();
        helpContentItemDaoConfig.clearIdentityScope();
        homeKnowContentDaoConfig.clearIdentityScope();
        homeKnowItemDaoConfig.clearIdentityScope();
        homeKnowDataDaoConfig.clearIdentityScope();
        homeKnowFunctionDaoConfig.clearIdentityScope();
    }

    public HelpCommendItemDao getHelpCommendItemDao() {
        return helpCommendItemDao;
    }

    public HelpContentItemDao getHelpContentItemDao() {
        return helpContentItemDao;
    }

    public HomeKnowContentDao getHomeKnowContentDao() {
        return homeKnowContentDao;
    }

    public HomeKnowItemDao getHomeKnowItemDao() {
        return homeKnowItemDao;
    }

    public HomeKnowDataDao getHomeKnowDataDao() {
        return homeKnowDataDao;
    }

    public HomeKnowFunctionDao getHomeKnowFunctionDao() {
        return homeKnowFunctionDao;
    }

}
