package com.vagrancys.learningassistant.db;

import java.util.List;
import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;
import org.greenrobot.greendao.query.Query;
import org.greenrobot.greendao.query.QueryBuilder;

import com.vargancys.learningassistant.db.game.GameSubjectItem;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "GAME_SUBJECT_ITEM".
*/
public class GameSubjectItemDao extends AbstractDao<GameSubjectItem, Long> {

    public static final String TABLENAME = "GAME_SUBJECT_ITEM";

    /**
     * Properties of entity GameSubjectItem.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property SubjectId = new Property(1, long.class, "subjectId", false, "SUBJECT_ID");
    }

    private Query<GameSubjectItem> gameSubjectContent_MItemsQuery;

    public GameSubjectItemDao(DaoConfig config) {
        super(config);
    }
    
    public GameSubjectItemDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"GAME_SUBJECT_ITEM\" (" + //
                "\"_id\" INTEGER PRIMARY KEY UNIQUE ," + // 0: id
                "\"SUBJECT_ID\" INTEGER NOT NULL );"); // 1: subjectId
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"GAME_SUBJECT_ITEM\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, GameSubjectItem entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getSubjectId());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, GameSubjectItem entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getSubjectId());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public GameSubjectItem readEntity(Cursor cursor, int offset) {
        GameSubjectItem entity = new GameSubjectItem( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getLong(offset + 1) // subjectId
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, GameSubjectItem entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setSubjectId(cursor.getLong(offset + 1));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(GameSubjectItem entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(GameSubjectItem entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(GameSubjectItem entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "mItems" to-many relationship of GameSubjectContent. */
    public List<GameSubjectItem> _queryGameSubjectContent_MItems(long subjectId) {
        synchronized (this) {
            if (gameSubjectContent_MItemsQuery == null) {
                QueryBuilder<GameSubjectItem> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.SubjectId.eq(null));
                gameSubjectContent_MItemsQuery = queryBuilder.build();
            }
        }
        Query<GameSubjectItem> query = gameSubjectContent_MItemsQuery.forCurrentThread();
        query.setParameter(0, subjectId);
        return query.list();
    }

}
