package com.vagrancys.learningassistant.db;

import java.util.List;
import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;
import org.greenrobot.greendao.query.Query;
import org.greenrobot.greendao.query.QueryBuilder;

import com.vargancys.learningassistant.db.home.HomeKnowHistory;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "HOME_KNOW_HISTORY".
*/
public class HomeKnowHistoryDao extends AbstractDao<HomeKnowHistory, Long> {

    public static final String TABLENAME = "HOME_KNOW_HISTORY";

    /**
     * Properties of entity HomeKnowHistory.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property DataId = new Property(1, long.class, "dataId", false, "DATA_ID");
    }

    private Query<HomeKnowHistory> homeKnowData_HomeKnowHistorysQuery;

    public HomeKnowHistoryDao(DaoConfig config) {
        super(config);
    }
    
    public HomeKnowHistoryDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"HOME_KNOW_HISTORY\" (" + //
                "\"_id\" INTEGER PRIMARY KEY UNIQUE ," + // 0: id
                "\"DATA_ID\" INTEGER NOT NULL );"); // 1: dataId
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"HOME_KNOW_HISTORY\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, HomeKnowHistory entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getDataId());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, HomeKnowHistory entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getDataId());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public HomeKnowHistory readEntity(Cursor cursor, int offset) {
        HomeKnowHistory entity = new HomeKnowHistory( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getLong(offset + 1) // dataId
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, HomeKnowHistory entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setDataId(cursor.getLong(offset + 1));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(HomeKnowHistory entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(HomeKnowHistory entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(HomeKnowHistory entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "homeKnowHistorys" to-many relationship of HomeKnowData. */
    public List<HomeKnowHistory> _queryHomeKnowData_HomeKnowHistorys(long dataId) {
        synchronized (this) {
            if (homeKnowData_HomeKnowHistorysQuery == null) {
                QueryBuilder<HomeKnowHistory> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.DataId.eq(null));
                homeKnowData_HomeKnowHistorysQuery = queryBuilder.build();
            }
        }
        Query<HomeKnowHistory> query = homeKnowData_HomeKnowHistorysQuery.forCurrentThread();
        query.setParameter(0, dataId);
        return query.list();
    }

}
