package com.vagrancys.learningassistant.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.vargancys.learningassistant.db.overview.OverViewListItem;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "OVER_VIEW_LIST_ITEM".
*/
public class OverViewListItemDao extends AbstractDao<OverViewListItem, Long> {

    public static final String TABLENAME = "OVER_VIEW_LIST_ITEM";

    /**
     * Properties of entity OverViewListItem.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Create = new Property(1, long.class, "create", false, "CREATE");
        public final static Property ParentId = new Property(2, long.class, "parentId", false, "PARENT_ID");
        public final static Property Title = new Property(3, String.class, "title", false, "TITLE");
        public final static Property MasterLevel = new Property(4, int.class, "masterLevel", false, "MASTER_LEVEL");
        public final static Property Level = new Property(5, int.class, "level", false, "LEVEL");
        public final static Property Study = new Property(6, boolean.class, "study", false, "STUDY");
        public final static Property Score = new Property(7, int.class, "score", false, "SCORE");
    }


    public OverViewListItemDao(DaoConfig config) {
        super(config);
    }
    
    public OverViewListItemDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"OVER_VIEW_LIST_ITEM\" (" + //
                "\"_id\" INTEGER PRIMARY KEY UNIQUE ," + // 0: id
                "\"CREATE\" INTEGER NOT NULL ," + // 1: create
                "\"PARENT_ID\" INTEGER NOT NULL ," + // 2: parentId
                "\"TITLE\" TEXT," + // 3: title
                "\"MASTER_LEVEL\" INTEGER NOT NULL ," + // 4: masterLevel
                "\"LEVEL\" INTEGER NOT NULL ," + // 5: level
                "\"STUDY\" INTEGER NOT NULL ," + // 6: study
                "\"SCORE\" INTEGER NOT NULL );"); // 7: score
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"OVER_VIEW_LIST_ITEM\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, OverViewListItem entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getCreate());
        stmt.bindLong(3, entity.getParentId());
 
        String title = entity.getTitle();
        if (title != null) {
            stmt.bindString(4, title);
        }
        stmt.bindLong(5, entity.getMasterLevel());
        stmt.bindLong(6, entity.getLevel());
        stmt.bindLong(7, entity.getStudy() ? 1L: 0L);
        stmt.bindLong(8, entity.getScore());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, OverViewListItem entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getCreate());
        stmt.bindLong(3, entity.getParentId());
 
        String title = entity.getTitle();
        if (title != null) {
            stmt.bindString(4, title);
        }
        stmt.bindLong(5, entity.getMasterLevel());
        stmt.bindLong(6, entity.getLevel());
        stmt.bindLong(7, entity.getStudy() ? 1L: 0L);
        stmt.bindLong(8, entity.getScore());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public OverViewListItem readEntity(Cursor cursor, int offset) {
        OverViewListItem entity = new OverViewListItem( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getLong(offset + 1), // create
            cursor.getLong(offset + 2), // parentId
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // title
            cursor.getInt(offset + 4), // masterLevel
            cursor.getInt(offset + 5), // level
            cursor.getShort(offset + 6) != 0, // study
            cursor.getInt(offset + 7) // score
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, OverViewListItem entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setCreate(cursor.getLong(offset + 1));
        entity.setParentId(cursor.getLong(offset + 2));
        entity.setTitle(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setMasterLevel(cursor.getInt(offset + 4));
        entity.setLevel(cursor.getInt(offset + 5));
        entity.setStudy(cursor.getShort(offset + 6) != 0);
        entity.setScore(cursor.getInt(offset + 7));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(OverViewListItem entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(OverViewListItem entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(OverViewListItem entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
