package com.vagrancys.learningassistant.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.vargancys.learningassistant.db.knowledge.TemporaryClassDb;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "TEMPORARY_CLASS_DB".
*/
public class TemporaryClassDbDao extends AbstractDao<TemporaryClassDb, Long> {

    public static final String TABLENAME = "TEMPORARY_CLASS_DB";

    /**
     * Properties of entity TemporaryClassDb.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, long.class, "id", true, "_id");
        public final static Property Class_id = new Property(1, int.class, "class_id", false, "CLASS_ID");
    }


    public TemporaryClassDbDao(DaoConfig config) {
        super(config);
    }
    
    public TemporaryClassDbDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"TEMPORARY_CLASS_DB\" (" + //
                "\"_id\" INTEGER PRIMARY KEY NOT NULL ," + // 0: id
                "\"CLASS_ID\" INTEGER NOT NULL );"); // 1: class_id
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"TEMPORARY_CLASS_DB\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, TemporaryClassDb entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getId());
        stmt.bindLong(2, entity.getClass_id());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, TemporaryClassDb entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getId());
        stmt.bindLong(2, entity.getClass_id());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.getLong(offset + 0);
    }    

    @Override
    public TemporaryClassDb readEntity(Cursor cursor, int offset) {
        TemporaryClassDb entity = new TemporaryClassDb( //
            cursor.getLong(offset + 0), // id
            cursor.getInt(offset + 1) // class_id
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, TemporaryClassDb entity, int offset) {
        entity.setId(cursor.getLong(offset + 0));
        entity.setClass_id(cursor.getInt(offset + 1));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(TemporaryClassDb entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(TemporaryClassDb entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(TemporaryClassDb entity) {
        throw new UnsupportedOperationException("Unsupported for entities with a non-null key");
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
